[package]
name = "tankrs"
version = "0.1.0"
authors = ["ming li <mingyli34@gmail.com>", "michael luo <mluogh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "server/src/main.rs"

[dependencies]
flatbuffers = "0.6.1"

[build-dependencies]
flatc-rust = "0.1.2"

