// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export enum Movement{
  Up= 0,
  Down= 1,
  Left= 2,
  Right= 3
};

/**
 * @constructor
 */
export class ActionRoot {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ActionRoot
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ActionRoot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ActionRoot= obj
 * @returns ActionRoot
 */
static getRootAsActionRoot(bb:flatbuffers.ByteBuffer, obj?:ActionRoot):ActionRoot {
  return (obj || new ActionRoot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ActionRoot= obj
 * @returns ActionRoot
 */
static getSizePrefixedRootAsActionRoot(bb:flatbuffers.ByteBuffer, obj?:ActionRoot):ActionRoot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ActionRoot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns Movement
 */
movement():Movement {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : Movement.Up;
};

/**
 * @param flatbuffers.Builder builder
 */
static startActionRoot(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param Movement movement
 */
static addMovement(builder:flatbuffers.Builder, movement:Movement) {
  builder.addFieldInt8(0, movement, Movement.Up);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endActionRoot(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishActionRootBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedActionRootBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createActionRoot(builder:flatbuffers.Builder, movement:Movement):flatbuffers.Offset {
  ActionRoot.startActionRoot(builder);
  ActionRoot.addMovement(builder, movement);
  return ActionRoot.endActionRoot(builder);
}
}
