on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Continuous integration

env:
  cargo-path: Cargo.toml

jobs:
  rust:
    name: rust_presubmit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      # fmt before build so it never checks autogen code
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path=${{env.cargo-path}} -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=${{env.cargo-path}}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=${{env.cargo-path}}
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=${{env.cargo-path}} -- -W clippy::all -W clippy::pedantic -D warnings

  build-ts:
    name: Build Typescript
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@master
      - run: yarn install
      - run: make all
        working-directory: ${{env.working-directory}}

  format-check:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run check-format
