on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Continuous integration

env:
  cargo-path: Cargo.toml

jobs:
  server-presubmit:
    name: server-presubmit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=${{env.cargo-path}}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=${{env.cargo-path}}
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path=${{env.cargo-path}} -- --check
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=${{env.cargo-path}} -- -W clippy::all -W clippy::pedantic -D warnings

  client-presubmit:
    name: client-presubmit
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@master
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npm run presubmit:ci
        working-directory: ${{env.working-directory}}

  global-format:
    name: global-format
    steps:
      - run: yarn install
      - run: yarn run check-format
