on: [push, pull_request]

name: Continuous integration

env:
  cargo-path: Cargo.toml

jobs:
  flatbuffers:
    name: Install Flatbuffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: google/flatbuffers
          ref: v1.12.0
      - name: cmake
        run: cmake -G "Unix Makefiles"
      - name: make
        run: make
      - name: executable
        run: chmod +x ./flatc
      - name: Upload flatc binary
        uses: actions/upload-artifact@v1
        with:
          name: flatbuffers
          path: flatc

  build:
    name: Build
    needs: flatbuffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download flatc binary
        uses: actions/download-artifact@v1
        with:
          name: flatbuffers
      - name: chmod
        run: chmod +x flatbuffers/flatc
      - name: add to path
        run: echo "::add-path::$(realpath flatbuffers)"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=${{env.cargo-path}}

  check:
    name: Check
    needs: flatbuffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download flatc binary
        uses: actions/download-artifact@v1
        with:
          name: flatbuffers
      - name: chmod
        run: chmod +x flatbuffers/flatc
      - name: add to path
        run: echo "::add-path::$(realpath flatbuffers)"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path=${{env.cargo-path}}

  test:
    name: Test Suite
    needs: flatbuffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download flatc binary
        uses: actions/download-artifact@v1
        with:
          name: flatbuffers
      - name: chmod
        run: chmod +x flatbuffers/flatc
      - name: add to path
        run: echo "::add-path::$(realpath flatbuffers)"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=${{env.cargo-path}}

  fmt:
    name: Rustfmt
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download flatc binary
        uses: actions/download-artifact@v1
        with:
          name: flatbuffers
      - name: chmod
        run: chmod +x flatbuffers/flatc
      - name: add to path
        run: echo "::add-path::$(realpath flatbuffers)"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=${{env.cargo-path}}
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path=${{env.cargo-path}} -- --check

  clippy:
    name: Clippy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download flatc binary
        uses: actions/download-artifact@v1
        with:
          name: flatbuffers
      - name: chmod
        run: chmod +x flatbuffers/flatc
      - name: add to path
        run: echo "::add-path::$(realpath flatbuffers)"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=${{env.cargo-path}} -- -W clippy::all -W clippy::pedantic -D warnings

  build-ts:
    name: Build Typescript
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run typecheck
        working-directory: ${{env.working-directory}}
      - run: yarn run build
        working-directory: ${{env.working-directory}}

  format-check:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run format
